# nixpacks.toml
node_version = "18"  # Use the appropriate Node.js version

[build]
command = "npm install && npm run build"  # Install dependencies and build the project

[serve]
command = "npx serve dist"  # Use a static server to serve the built files from the dist directory
port = 3000  # The port to serve the application
