export const chief_complains = [
  'hyperactivity',
  'delayed speech',
  'speech problem',
  'behavioral problem',
  'poor school performance',
  'sleep problem',
  'eating problem',
]
export const durations = [
  '1 week',
  '2 weeks',
  '3 weeks',
  '1 month',
  '2 months',
  '3 months',
  'several months',
  '1 year',
  '2 years',
  '3 years',
  'several years',
]
export const sourceOfInfo = [
  'patient',
  'mother',
  'father',
  'both parents',
  'grandmother',
  'grandfather',
  'sister',
  'brother',
  'neighbor',
  'unrelated',
]

export const courseSuggestions = [
  'Acute',
  'Chronic',
  'Episodic',
  'Progressive',
  'Recurrent',
  'Worsening',
  'Stable',
  'Improving',
  'Fluctuating',
  'Unpredictable',
]

export const circumstancesSuggestions = [
  'Stressful events',
  'Trauma',
  'Recent changes',
  'Social support',
  'Work environment',
  'Family situation',
  'Financial situation',
  'Legal issues',
  'Health conditions',
  'Living situation',
]

export const vegetativeSymptomsSuggestions = [
  'Sleep disturbances',
  'Appetite changes',
  'Fatigue',
  'Low energy',
  'Psychomotor agitation',
  'Psychomotor retardation',
  'Libido changes',
  'Weight changes',
  'Menstrual changes',
  'Diurnal variation',
]

export const associatedSymptomsSuggestions = [
  'Anxiety',
  'Depression',
  'Mania',
  'Panic attacks',
  'Psychosis',
  'Obsessions/compulsions',
  'Somatic symptoms',
  'Cognitive symptoms',
  'Affective symptoms',
  'Behavioral symptoms',
]

export const functioningSuggestions = [
  'Work/school',
  'Relationships',
  'Self-care',
  'Social activities',
  'Leisure activities',
  'Concentration',
  'Memory',
  'Decision-making',
  'Problem-solving',
  'Independence',
]

export const relationshipsSuggestions = [
  'Family',
  'Friends',
  'Romantic partners',
  'Colleagues',
  'Neighbors',
  'Healthcare providers',
  'Community supports',
  'Pets',
  'Support groups',
  'Mentors',
]

export const treatmentsSuggestions = [
  'Medications',
  'Psychotherapy',
  'Hospitalization',
  'ECT',
  'TMS',
  'Sleep hygiene',
  'Dietary changes',
]

export const substancesSuggestions = [
  'Alcohol',
  'Cannabis',
  'Cocaine',
  'Amphetamines',
  'Opioids',
  'Hallucinogens',
  'Sedatives/hypnotics',
  'Tobacco/nicotine',
  'Caffeine',
  'Prescription drugs',
]

export const riskAssessmentSuggestions = [
  'Suicidal ideation',
  'Self-harm behaviors',
  'Homicidal ideation',
  'Violence/aggression',
  'Impulsivity',
  'Risky behaviors',
  'Substance abuse',
  'Unsafe sexual practices',
  'Non-adherence to treatment',
  'Financial difficulties',
]

export const familyHistorySuggestions = [
  'Heart disease',
  'Diabetes',
  'Cancer',
  'High blood pressure',
  'Stroke',
  "Alzheimer's disease",
  'Mental illness',
  'Substance abuse',
  'Allergies',
  'Autoimmune diseases',
  'Childhood illness',
  'Heart disease',
  'Diabetes',
  'Cancer',
  'High blood pressure',
  'Stroke',
  "Alzheimer's disease",
  'Mental illness',
  'Substance abuse',
  'Allergies',
  'Autoimmune diseases',
  'Childhood illness',
  'Autism',
  'ADHD',
  'Asthma',
  'Cerebral palsy',
  'Cystic fibrosis',
  'Down syndrome',
  'Epilepsy',
  'Juvenile diabetes',
  'Muscular dystrophy',
  'Sickle cell anemia',
]

export const pastPsychiatricHistorySuggestions = [
  'Depression',
  'Anxiety disorder',
  'Bipolar disorder',
  'Schizophrenia',
  'OCD',
  'PTSD',
  'ADHD',
  'ASD',
  'Eating disorder',
  'Substance use disorder',
  'Personality disorder',
  'Panic disorder',
  'Phobia',
  'Psychosis',
  'Trauma',
  'Self-harm',
  'Suicidal ideation/attempts',
]

export const pastMedicalHistorySuggestions = [
  'Hypertension',
  'Diabetes',
  'Heart disease',
  'Stroke',
  'Cancer',
  'Asthma',
  'COPD',
  'Thyroid disorders',
  'Gastrointestinal disorders',
  'Liver disease',
  'Kidney disease',
  'Arthritis',
  'Osteoporosis',
  'Autoimmune disorders',
  'Allergies',
  'Infectious diseases',
  'Neurological disorders',
  'HIV/AIDS',
  'Hepatitis',
  'Anemia',
  'Malnutrition',
  'Hemorrhagic disorders',
  'Genetic disorders',
  'Traumatic injuries',
  'Surgery history',
  'Hospitalizations',
  'Medication history',
  'Blood transfusions',
  'Immunizations',
  'Psychosocial stressors impacting health',
]

export const pastSurgicalHistorySuggestions = [
  'Appendectomy',
  'Cholecystectomy',
  'Hernia repair',
  'Joint replacement surgery',
  'Spinal surgery',
  'Cardiac bypass surgery',
  'Gastric bypass surgery',
  'Hysterectomy',
  'Cesarean section',
  'Prostatectomy',
  'Mastectomy',
  'Lung surgery',
  'Brain surgery',
  'Kidney transplant',
  'Liver transplant',
  'Orthopedic surgery',
  'Plastic surgery',
  'Cosmetic surgery',
  'Reconstructive surgery',
  'Exploratory surgery',
  'Biopsy',
  'Amputation',
  'Eye surgery',
  'Dental surgery',
  'ENT surgery',
  'Colon resection',
  'Rectal surgery',
  'Urological surgery',
  'Vascular surgery',
  'Thoracic surgery',
]

export const accommodationSuggestions = [
  'House',
  'Apartment',
  'Single-family house',
  'Studio apartment',
  'Group home',
  'Hotel',
  "Friend/relative's house",
  'Homeless',
  'Tiny house',
]

export const financeSuggestions = ['good', 'bad']

export const differentialDiagnosis = [
  'Major Depressive Disorder',
  'Bipolar Disorder',
  'Generalized Anxiety Disorder',
  'Panic Disorder',
  'Social Anxiety Disorder',
  'OCD',
  'PTSD',
  'Schizophrenia',
  'ADHD',
  'ASD',
  'Eating Disorders',
  'Anorexia Nervosa',
  'Bulimia Nervosa',
  'Substance Use Disorders',
  'Trauma- and Stressor-Related Disorders',
  'Neurodevelopmental Disorders',
  'Sleep-Wake Disorders',
  'Neurocognitive Disorders',
  'Paranoid Personality Disorder',
  'Schizoid Personality Disorder',
  'Schizotypal Personality Disorder',
  'Antisocial Personality Disorder',
  'Borderline Personality Disorder',
  'Histrionic Personality Disorder',
  'Narcissistic Personality Disorder',
  'Avoidant Personality Disorder',
  'Dependent Personality Disorder',
  'Obsessive-Compulsive Personality Disorder',
]

export const lab_tests = [
  'Complete Blood Count (CBC)',
  'Basic Metabolic Panel (BMP)',
  'Comprehensive Metabolic Panel (CMP)',
  'Lipid Profile',
  'Thyroid Function Tests',
  'Urinalysis',
  'Blood Glucose',
  'Liver Function Tests (LFTs)',
  'Coagulation Profile',
  'Serum Electrolytes',
  'C-reactive Protein (CRP)',
  'Hemoglobin A1c (HbA1c)',
]

export const cities = [
  'بغداد',
  'النجف',
  'بابل',
  'كربلاء',
  'الأنبار',
  'البصرة',
  'المثنى',
  'القادسية',
  'أربيل',
  'السليمانية',
  'دهوك',
  'ذي قار',
  'ديالى',
  'كركوك',
  'ميسان',
  'نينوى',
  'صلاح الدين',
  'واسط',
]

export const baghdadRegions = [
  // أ
  'ابو دشير',
  'الأعظمية',
  'الباب الشرقي',
  'البلديات',
  'البو عيثة',
  'البياع',
  'الثعالبة',
  'الجادرية',
  'الحارثية',
  'الحبيبية',
  'الخطيب',
  'الدهاليك',
  'الدورة',
  'الرشاد',
  'الرصافة',
  'الرضوانية',
  'الزعفرانية',
  'السعدون',
  'السويب',
  'السيدية',
  'الشالجية',
  'الشعب',
  'الشعلة',
  'الصالحية',
  'الطوبجي',
  'العامرية',
  'العبيدي',
  'العطيفية',
  'الغدير',
  'الغزالية',
  'الفضيلية',
  'الكاظمية',
  'الكرادة الشرقية',
  'الكرخ',
  'الكمالية',
  'المنطقة الخضراء',
  'النهروان',
  'الهبنة',
  'الوزيرية',
  'الوشاش',
  'اليرموك',
  'اليوسفية',
  // ب
  'باب الآغا',
  'باب المعظم',
  'بغداد الجديدة',
  // ج
  'جرف النداف',
  'جسر ديالى',
  'جكوك',
  'جميلة',
  // ح
  'حافظ القاضي',
  'حي أور',
  'حي الآثوريين',
  'حي الأمين',
  'حي الإعلام',
  'حي الجامعة',
  'حي الجمبلاطية',
  'حي الجهاد',
  'حي الحرية',
  'حي الخضراء',
  'حي السريان',
  'حي الشرطة',
  'حي الشهداء',
  'حي الصحة',
  'حي الضباط',
  'حي العامل',
  'حي العدل',
  'حي الفضل',
  'حي القاهرة',
  'حي المهندسين',
  'حي الميكانيك',
  'حي تونس',
  'حي طارق',
  // د
  'دور السود',
  // ر
  'راغبة خاتون',
  // ز
  'زيونة',
  // س
  'سبع أبكار',
  'سبع قصور',
  // ش
  'شارع الرشيد',
  'شارع الكفاح',
  'شارع المتنبي',
  'شارع حيفا',
  'شارع فلسطين',
  // ع
  'عرب جبور',
  // ق
  'قصر الزقورة',
  // ك
  'كرادة مريم',
  // م
  'محلة الدنكجية',
  'مسبح الأمانة',
  'مناطق بغداد',
  // ن
  'ناحية المأمون',
  'ناحية المنصور',
]

export const childEducation = [
  'Preschool',
  "Didn't Attend School",
  '1st grade',
  '2nd grade',
  '3rd grade',
  '4th grade',
  '5th grade',
  '6th grade',
  'Primary School',
  'Secondary School',
  'School Dropout',
]

export const adultEducation = [
  'Illiterate',
  'Primary School',
  'Secondary School',
  'Diploma',
  'Bachelor',
  'Master',
  'Doctorate',
]

export const childFamilyHx = [
  'ASD',
  'ADHD',
  'ID',
  'Communication disorders',
  'Speech delay',
  'Epilepsy',
  'Psychotic disorders',
  'Mood disorders',
  'Anxiety disorders',
  'Substances',
]

export const childDdx = [
  'ASD',
  'ADHD',
  'Intellectual Disability',
  'Global Developmental Delay',
  'Language Disorder',
  'Speech Sound Disorder',
  'Childhood-Onset Fluency Disorder (Stuttering)',
  'Social Pragmatic Communication Disorder',
  'Specific Learning Disorder',
  'Developmental Coordination disorder ',
  'Stereotypic Movement Disorder',
  'Tic Disorders',
]

export const occupationSuggestions = [
  'housewife',
  'unemployed',
  'government employee',
  'private employee',
  'worker',
  'nurse',
  'engineer',
  'pharmacist',
  'college',
  'student',
]

export const year1List = {
  'PERSONAL-SOCIAL': [
    'DRINK FROM CUP',
    'IMITATES ACTIVITIES',
    'PLAY BALL WITH EXAMINER',
    'WAVE BYE-BYE',
    'INDICATE WANTS',
    'PLAY PAT A CAKE',
    'FEED SELF',
    'WORK FOR TOY',
    'REGARD OWN HAND',
    'SMILE SPONTANEOUSLY',
    'SMILE RESPONSIVELY',
    'REGARD FACE',
  ],
  'FINE MOTOR-ADAPTIVE': [
    'SCRIBBLES',
    'PUT BLOCK IN CUP',
    'BANG 2 CUBES',
    'THUMB FINGER GRASP',
    'TAKE 2 CUPS',
    'PASS CUBE',
    'RAKE RAISIN',
    'LOOK FOR YARN',
    'REACHES',
    'REGARD RAISIN',
    'FOLLOW 180',
    'HANDS TOGETHER',
    'GRASP RATTLE',
    'FOLLOW PAST MIDLINE',
    'FOLLOW TO MIDLINE',
  ],
  LANGUAGE: [
    '3 WORDS',
    '2 WORDS',
    '1 WORD',
    'DADA MAMA SPECIFIC',
    'JABBERS',
    'COMBINE SYLLABLES',
    'DADA MAMA NON-SPECIFIC',
    'IMITATE SPEECH SOUND',
    'SINGLE SYLLABLES',
    'TURN TO VOICE',
    'TURN TO RATTLING',
    'SQUEALS',
    'LAUGHS',
    'OOO/AAH',
    'VOCALIZES',
    'RESPOND TO BELL',
  ],
  'GROSS MOTOR': [
    'STAND ALONE',
    'STAND 2 SEC',
    'GET TO SITTING',
    'PULL TO STAND',
    'STAND HOLDING ON',
    'SIT NO SUPPORT',
    'PULL TO SIT',
    'ROLL OVER',
    'CHEST UP ARM SUPPORT',
    'BEAR WEIGHT ON LEGS',
    'SIT HEAD STEADY',
    'HEAD UP 90',
    'HEAD UP 45',
    'LIFT HEAD',
    'EQUAL MOVEMENTS',
  ],
}

export const year2List = {
  'PERSONAL-SOCIAL': [
    'WASH & DRY HANDS',
    'BRUSH TEETH',
    'PUT ON CLOTHING',
    'FEED DOLL',
    'REMOVE GARMENT',
    'USE SPOON/FORK',
    'HELP IN HOUSE',
  ],
  'FINE MOTOR-ADAPTIVE': [
    'TOWER 6 CUBES',
    'TOWER 4 CUBES',
    'TOWER 2 CUBES',
    'DUMP RAISIN',
  ],
  LANGUAGE: [
    'KNOW 2 ACTIONS',
    'NAME 4 PICTURES',
    'SPEECH HALF UNDERSTANDABLE',
    'POINT 4 PICTURES',
    'BODY PARTS-6',
    'NAME 1 PICTURE',
    'COMBINE WORDS',
    'POINT 2 PICTURES',
    '6 WORDS',
  ],
  'GROSS MOTOR': [
    'THROW BALL OVERHEAD',
    'JUMP UP',
    'KICK BALL FORWARD',
    'WALK UP STEPS',
    'RUNS',
    'WALK BACKWARD',
    'WALK WELL',
    'STOOP AND RECOVER',
  ],
}

export const year3List = {
  'PERSONAL-SOCIAL': [
    'PLAY BOARD/CARD GAME',
    'BRUSH TEETH NO HELP',
    'PUT ON TSHIRT',
    'NAME FRIEND',
  ],
  'FINE MOTOR-ADAPTIVE': [
    'PICK LONGER LINE',
    'COPY +',
    'DRAW PERSON',
    'COPY CIRCLE',
    'THUMB WIGGLE',
    'TOWER 8 CUBES',
    'IMITATE VERTICAL LINE',
  ],
  LANGUAGE: [
    'KNOW 3 ADJECTIVES',
    'DEFINE 5 WORDS',
    'SPEECH ALL UNDERSTANDABLE',
    'KNOW 4 ACTIONS',
    'USE 3 OBJECTS',
    'COUNT 1 BLOCK',
    'USE 2 OBJECTS',
    'NAME 1 COLOR',
    'KNOW 2 ADJECTIVES',
  ],
  'GROSS MOTOR': [
    'HOPS',
    'BALANCE EACH FOOT 3 SEC',
    'BALANCE EACH FOOT 2 SEC',
    'BALANCE EACH FOOT 1 SEC',
    'BROAD JUMP',
  ],
}

export const year4List = {
  'PERSONAL-SOCIAL': ['PREPARE CEREAL', 'DRESS NO HELP'],
  'FINE MOTOR-ADAPTIVE': [
    'COPY SQUARE',
    'DRAW PERSON 6 PARTS',
    'COPY SQUARE DEMONSTRATED',
  ],
  LANGUAGE: ['DEFINE 7 WORDS', 'OPPOSITE 2', 'COUNT 5 BLOCKS'],
  'GROSS MOTOR': [
    'HEEL TO TOE WALK',
    'BALANCE EACH FOOT 5 SEC',
    'BALANCE EACH FOOT 4 SEC',
  ],
}

export const year5List = {
  'PERSONAL-SOCIAL': ['PREPARE CEREAL'],
  'FINE MOTOR-ADAPTIVE': [
    'COPY SQUARE',
    'DRAW PERSON 6 PARTS',
    'COPY SQUARE DEMONSTRATED',
  ],
  LANGUAGE: ['DEFINE 7 WORDS', 'OPPOSITE 2', 'COUNT 5 BLOCKS'],
  'GROSS MOTOR': [
    'BALANCE EACH FOOT 6 SEC',
    'HEEL TO TOE WALK',
    'BALANCE EACH FOOT 5 SEC',
    'BALANCE EACH FOOT 4 SEC',
  ],
}

export const peripartumList = {
  PRENATAL: [
    'RECURRENT ABORTIONS',
    'HYPERTENSION',
    'GESTATIONAL DM',
    'ECLAMPSIA',
    'THYROID DISORDER',
    'RADIATION EXPOSURE',
    'HEMORRHAGE',
    'ANEMIA',
    'PROGESTRONES',
    'VACCINES',
    'DEPRESSION',
    'SMOKING',
    'FAMILY CONFLICTS',
    'CHRONIC DISORDER',
  ],
  NATAL: [
    'COMPLETE 37-42 WEEKS',
    'EARLY LESS THAN 37',
    'LATE MORE THAN 42',
    'NORAML WIGHT',
    'EXCESSIVE WEIGHT',
    'LOW WEIGHT',
    'CYANOSIS',
    'RESUSITATION',
    'PEDIATRIC CARE UNIT',
    'BREACH',
    'NATURAL BIRTH AT HOME',
    'NATURAL BIRTH AT HOSPITAL',
    'CESAREAN SECTION',
    'DIFFICULT BIRTH',
  ],
  POSTNATAL: [
    'ADMISSION',
    'SEVERE INFECTIONS',
    'LABORED BREATHING',
    'CONVUSLTIONS',
    'CYANOSIS',
    'JAUNDICE',
    'LIGHT THERAPY',
    'BLOOD EXCHANGE',
    'HYPTONIC MUSCLES',
    'BIRTH DEFECTS',
    'GOOD SLEEP',
    'BAD SLEEP',
    'NATURAL FEEDING',
    'ARTIFICIAL FORMULA',
    'DIFFICULT WEANING',
  ],
}
