export const chief_complains = [
  "hyperactivity",
  "delayed speech",
  "speech problem",
  "behavioral problem",
  "poor school performance",
  "sleep problem",
  "eating problem",
];
export const durations = [
  "1 week",
  "2 weeks",
  "3 weeks",
  "1 month",
  "2 months",
  "3 months",
  "several months",
  "1 year",
  "2 years",
  "3 years",
  "several years",
];
export const sourceOfInfo = [
  "patient",
  "mother",
  "father",
  "both parents",
  "grandmother",
  "grandfather",
  "sister",
  "brother",
  "neighbor",
  "unrelated",
];

export const courseSuggestions = [
  "Acute",
  "Chronic",
  "Episodic",
  "Progressive",
  "Recurrent",
  "Worsening",
  "Stable",
  "Improving",
  "Fluctuating",
  "Unpredictable",
];

export const circumstancesSuggestions = [
  "Stressful events",
  "Trauma",
  "Recent changes",
  "Social support",
  "Work environment",
  "Family situation",
  "Financial situation",
  "Legal issues",
  "Health conditions",
  "Living situation",
];

export const vegetativeSymptomsSuggestions = [
  "Sleep disturbances",
  "Appetite changes",
  "Fatigue",
  "Low energy",
  "Psychomotor agitation",
  "Psychomotor retardation",
  "Libido changes",
  "Weight changes",
  "Menstrual changes",
  "Diurnal variation",
];

export const associatedSymptomsSuggestions = [
  "Anxiety",
  "Depression",
  "Mania",
  "Panic attacks",
  "Psychosis",
  "Obsessions/compulsions",
  "Somatic symptoms",
  "Cognitive symptoms",
  "Affective symptoms",
  "Behavioral symptoms",
];

export const functioningSuggestions = [
  "Work/school",
  "Relationships",
  "Self-care",
  "Social activities",
  "Leisure activities",
  "Concentration",
  "Memory",
  "Decision-making",
  "Problem-solving",
  "Independence",
];

export const relationshipsSuggestions = [
  "Family",
  "Friends",
  "Romantic partners",
  "Colleagues",
  "Neighbors",
  "Healthcare providers",
  "Community supports",
  "Pets",
  "Support groups",
  "Mentors",
];

export const treatmentsSuggestions = [
  "Medications",
  "Psychotherapy",
  "Hospitalization",
  "ECT",
  "TMS",
  "Sleep hygiene",
  "Dietary changes",
];

export const substancesSuggestions = [
  "Alcohol",
  "Cannabis",
  "Cocaine",
  "Amphetamines",
  "Opioids",
  "Hallucinogens",
  "Sedatives/hypnotics",
  "Tobacco/nicotine",
  "Caffeine",
  "Prescription drugs",
];

export const riskAssessmentSuggestions = [
  "Suicidal ideation",
  "Self-harm behaviors",
  "Homicidal ideation",
  "Violence/aggression",
  "Impulsivity",
  "Risky behaviors",
  "Substance abuse",
  "Unsafe sexual practices",
  "Non-adherence to treatment",
  "Financial difficulties",
];

export const familyHistorySuggestions = [
  "Heart disease",
  "Diabetes",
  "Cancer",
  "High blood pressure",
  "Stroke",
  "Alzheimer's disease",
  "Mental illness",
  "Substance abuse",
  "Allergies",
  "Autoimmune diseases",
  "Childhood illness",
  "Heart disease",
  "Diabetes",
  "Cancer",
  "High blood pressure",
  "Stroke",
  "Alzheimer's disease",
  "Mental illness",
  "Substance abuse",
  "Allergies",
  "Autoimmune diseases",
  "Childhood illness",
  "Autism",
  "ADHD",
  "Asthma",
  "Cerebral palsy",
  "Cystic fibrosis",
  "Down syndrome",
  "Epilepsy",
  "Juvenile diabetes",
  "Muscular dystrophy",
  "Sickle cell anemia",
];

export const pastPsychiatricHistorySuggestions = [
  "Depression",
  "Anxiety disorder",
  "Bipolar disorder",
  "Schizophrenia",
  "OCD",
  "PTSD",
  "ADHD",
  "ASD",
  "Eating disorder",
  "Substance use disorder",
  "Personality disorder",
  "Panic disorder",
  "Phobia",
  "Psychosis",
  "Trauma",
  "Self-harm",
  "Suicidal ideation/attempts",
];

export const pastMedicalHistorySuggestions = [
  "Hypertension",
  "Diabetes",
  "Heart disease",
  "Stroke",
  "Cancer",
  "Asthma",
  "Chronic obstructive pulmonary disease (COPD)",
  "Thyroid disorders",
  "Gastrointestinal disorders",
  "Liver disease",
  "Kidney disease",
  "Arthritis",
  "Osteoporosis",
  "Autoimmune disorders",
  "Allergies",
  "Infectious diseases",
  "Neurological disorders",
  "HIV/AIDS",
  "Hepatitis",
  "Anemia",
  "Malnutrition",
  "Hemorrhagic disorders",
  "Genetic disorders",
  "Traumatic injuries",
  "Surgery history",
  "Hospitalizations",
  "Medication history",
  "Blood transfusions",
  "Immunizations",
  "Psychosocial stressors impacting health",
];

export const pastSurgicalHistorySuggestions = [
  "Appendectomy",
  "Cholecystectomy",
  "Hernia repair",
  "Joint replacement surgery",
  "Spinal surgery",
  "Cardiac bypass surgery",
  "Gastric bypass surgery",
  "Hysterectomy",
  "Cesarean section",
  "Prostatectomy",
  "Mastectomy",
  "Lung surgery",
  "Brain surgery",
  "Kidney transplant",
  "Liver transplant",
  "Orthopedic surgery",
  "Plastic surgery",
  "Cosmetic surgery",
  "Reconstructive surgery",
  "Exploratory surgery",
  "Biopsy",
  "Amputation",
  "Eye surgery",
  "Dental surgery",
  "ENT surgery",
  "Colon resection",
  "Rectal surgery",
  "Urological surgery",
  "Vascular surgery",
  "Thoracic surgery",
];

export const accommodationSuggestions = [
  "House",
  "Apartment",
  "Single-family house",
  "Studio apartment",
  "Group home",
  "Hotel",
  "Friend/relative's house",
  "Homeless",
  "Tiny house",
];

export const financeSuggestions = [
  "Bank account",
  "Savings account",
  "Checking account",
  "Credit union",
  "Investment account",
  "Retirement account",
  "Brokerage account",
  "Money market account",
  "Certificate of deposit (CD)",
];

export const differentialDiagnosis = [
  "Major Depressive Disorder",
  "Bipolar Disorder",
  "Generalized Anxiety Disorder",
  "Panic Disorder",
  "Social Anxiety Disorder",
  "OCD",
  "PTSD",
  "Schizophrenia",
  "ADHD",
  "ASD",
  "Eating Disorders",
  "Anorexia Nervosa",
  "Bulimia Nervosa",
  "Substance Use Disorders",
  "Trauma- and Stressor-Related Disorders",
  "Neurodevelopmental Disorders",
  "Sleep-Wake Disorders",
  "Neurocognitive Disorders",
  "Paranoid Personality Disorder",
  "Schizoid Personality Disorder",
  "Schizotypal Personality Disorder",
  "Antisocial Personality Disorder",
  "Borderline Personality Disorder",
  "Histrionic Personality Disorder",
  "Narcissistic Personality Disorder",
  "Avoidant Personality Disorder",
  "Dependent Personality Disorder",
  "Obsessive-Compulsive Personality Disorder",
];

export const lab_tests = [
  "Complete Blood Count (CBC)",
  "Basic Metabolic Panel (BMP)",
  "Comprehensive Metabolic Panel (CMP)",
  "Lipid Profile",
  "Thyroid Function Tests",
  "Urinalysis",
  "Blood Glucose",
  "Liver Function Tests (LFTs)",
  "Coagulation Profile",
  "Serum Electrolytes",
  "C-reactive Protein (CRP)",
  "Hemoglobin A1c (HbA1c)",
];
